user-blog/config/routes.rb
UserBlog::Application.routes.draw do
  get "comments/new"

  resources :blogs do
    resources :comments
  end

end

user-blog/app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :content, :title, :tags_attributes
  has_many :comments, :dependent => :destroy
  has_many :tags
  validates_presence_of :title, :content

  accepts_nested_attributes_for :tags, :allow_destroy => true,
                                :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

user-blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
  attr_accessible :replay_by, :replay_content

  validates_presence_of :replay_by, :replay_content
end

user-blog/app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :blog
  attr_accessible :content
end

user-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

user-blog/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :set_blog, :only => [:edit, :edit, :destroy, :show, :update]

  def index
    @blogs=Blog.all
  end

  def show

  end

  def new
    @blog=Blog.new
  end

  def edit
  end

  def update
    if @blog.update_attributes(params[:blog])
      redirect_to(blog_path(@blog))
    end
  end

  def create
    @blog=Blog.new(params[:blog])
    if @blog.save
      redirect_to(blog_path(@blog))
    end
  end

  def destroy
    @blog.delete
    redirect_to(blogs_path)
  end

  private
  def set_blog
    @blog=Blog.find(params[:id])
  end
end

user-blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @blog=Blog.find(params[:blog_id])
    @comment=@blog.comments.new(params[:comment])
    if @comment.save
      redirect_to blog_path(@blog)
    end
  end

  def destroy
    @blog=Blog.find(params[:blog_id])
    @comment= @blog.comments.find(params[:id])
    @comment.delete
    redirect_to blog_path(@blog)
  end
end

user-blog/app/helpers/application_helper.rb
module ApplicationHelper
end

user-blog/app/helpers/blogs_helper.rb
module BlogsHelper
end

user-blog/app/helpers/comments_helper.rb
module CommentsHelper
end

user-blog/app/views/blogs/_form.html.erb
<div>
  <% @blog.tags.build %>
  <%= form_for @blog do |f| %>
      <%= f.label "标题" %>
      <%= f.text_field :title %>
      <%= f.label "内容" %>
      <%= f.text_field :content %>
      <%= render :partial => "tags/form",
                 :locals => {:form => f}
      %>

      <%= f.submit "提交" %>
  <% end %>
</div>

user-blog/app/views/blogs/edit.html.erb
<h1>Blogs#edit</h1>
<%= render "form" %>
<%= link_to "回首页", blogs_path %>

user-blog/app/views/blogs/index.html.erb
<h1>Blogs#index</h1>
<ul>
  <% @blogs.each do |blog| %>
      <li>
        <%= blog.title %>
        <br/>
        <%= blog.content %>
        <%= link_to "详细", blog_path(blog) %>
        <%= link_to "修改", edit_blog_path(blog) %>
        <%= link_to "删除", blog_path(blog), :method => :delete, data: {confirm: "are you sure?"} %>
      </li>
  <% end %>
  <%= link_to "新增", new_blog_path %>
</ul>

user-blog/app/views/blogs/new.html.erb
<h1>Blogs#new</h1>
<%= render "form" %>

<%= link_to "回首页", blogs_path %>

user-blog/app/views/blogs/show.html.erb
<div>
  <div>详细内容</div>
  <%= @blog.title %>
  <br/>
  <%= @blog.content %>
  <div>
    <%= @blog.tags.map { |t| t.content }.join(",") %>
  </div>
  <% unless @blog.comments.empty? %>
      <div class="replay">
        <ul>
          <% @blog.comments.each do |replay| %>
              <li>
                <%= replay.replay_content %>
                :<%= replay.replay_by %> <%= button_to "删除", [@blog, replay], :method => :delete, data: {confirm: "are you sure?"} %>
              </li>
          <% end %>
        </ul>
      </div>
  <% end %>
</div>

<%= form_for [@blog, @blog.comments.build] do |f| %>
    <%= f.label "姓名" %>
    <%= f.text_field :replay_by %>
    <%= f.label "内容" %>
    <%= f.text_field :replay_content %>
    <%= f.submit "提交" %>
<% end %>
<div>
  <%= link_to "回首页", blogs_path %>
  <%= link_to "修改", edit_blog_path(@blog) %>
</div>

user-blog/app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

user-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

user-blog/app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
    <%= tag_form.label :content, "tag:" %>
    <%= tag_form.text_field :content %>
<% end %>